version: "3.5"
services:
  mongo:
    image: mongo
    ports:
      - "8081:8081"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    volumes:
      - ./data/db:/data/db
      - ./cwiczenia2.json:/data/cwiczenia2.json
      - ./tasks:/root/tasks
# In the container type:
# mongoimport --file /data/cwiczenia2.json --db nbd --jsonArray -c people --authenticationDatabase admin -u admin -p admin
# mongo --authenticationDatabase admin -u admin -p admin
